/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ADMOB_AUTODEFS_H
#define ADMOB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADMOB_NAME "admob"
#define S3E_EXT_ADMOB_HASH 0xf12fd48

#endif /* !ADMOB_AUTODEFS_H */
