/*
 * Copyright (C) 2001-2011 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_ADMOB_H
#define S3E_EXT_ADMOB_H

#include <s3eTypes.h>

typedef enum Admob_AdSize
{

    Admob_GAD_SIZE_320x50  = 1,
    Admob_GAD_SIZE_300x250 = 2,
    Admob_GAD_SIZE_468x60  = 3,
    Admob_GAD_SIZE_728x90  = 4,

} Admob_AdSize;

typedef enum Admob_Orientation
{

    Admob_Orientation_Portrait  = 0,
    Admob_GAD_SIZE_Landscape = 1,
    Admob_GAD_SIZE_PortraitDown  = 2,
    Admob_GAD_SIZE_LandscapeDown  = 3,

} Admob_Orientation;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the admob extension is available.
 */
s3eBool admobAvailable();

s3eResult admob_init(const char* pub_id, int ad_type, int orientation, int x, int y);

s3eResult admob_resize(int ad_type);

s3eResult admob_show();

s3eResult admob_refresh();

s3eResult admob_hide();

s3eResult admob_move(int orientation, int x, int y);

S3E_END_C_DECL

#endif /* !S3E_EXT_ADMOB_H */
